name: w_transport
version: 2.8.0

description: >
  Transport library for sending HTTP requests and opening WebSockets.
  Platform-independent with builtin support for browser and Dart VM (even
  supports SockJS). Includes mock utilities for testing.

homepage: https://github.com/Workiva/w_transport

authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Dustin Lessard <dustin.lessard@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Jay Udey <jay.udey@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>

environment:
  sdk: ">=1.14.0 <2.0.0"

dependencies:
  fluri: ^1.1.0
  http_parser: ">=2.2.0 <4.0.0"
  mime: ^0.9.3
  sockjs_client:
    git:
      url: https://github.com/Workiva/sockjs-dart-client.git
      ref: 0.3.1

dev_dependencies:
  ansicolor: ^0.0.9
  args: ^0.13.0
  browser: ^0.10.0+2
  coverage: ^0.7.9
  dart_dev: ^1.4.0
  dart_style: ^0.2.4
  http_server: ^0.9.5+1
  mockito: ^0.11.0
  path: ^1.3.9
  react: ^0.6.1
  test: ^0.12.15
  uuid: ^0.5.0
