name: w_transport
version: 3.1.2

description: >
  Transport library for sending HTTP requests and opening WebSockets.
  Platform-independent with builtin support for browser and Dart VM (even
  supports SockJS). Includes mock utilities for testing.

homepage: https://github.com/Workiva/w_transport

authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Dustin Lessard <dustin.lessard@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Jay Udey <jay.udey@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>

environment:
  sdk: ">=1.14.0 <2.0.0"

dependencies:
  fluri: ^1.2.2
  http_parser: '>=2.2.0 <4.0.0'
  meta: ^1.1.0
  mime: ^0.9.3
  sockjs_client_wrapper:
    git:
      url: git@github.com:Workiva/sockjs_client_wrapper.git
      ref: initial_implementation
  # sockjs_client:
  #   git:
  #     url: https://github.com/Workiva/sockjs-dart-client.git
  #     ref: 0.3.2

dev_dependencies:
  browser: ^0.10.0+2
  coverage: ^0.7.9
  dart_dev: ^1.7.7
  dart_style: ^1.0.6
  dependency_validator: ^1.0.0
  http_server: ^0.9.6
  mockito: ^2.0.2
  react: ^0.6.1
  test: ^0.12.23+1
  uuid: ^0.5.3

transformers:
- test/pub_serve:
    $include: test/**_test.dart
