name: w_transport
version: 3.2.6

description: >
  Transport library for sending HTTP requests and opening WebSockets.
  Platform-independent with builtin support for browser and Dart VM (even
  supports SockJS). Includes mock utilities for testing.

homepage: https://github.com/Workiva/w_transport

authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Dustin Lessard <dustin.lessard@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Jay Udey <jay.udey@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>

environment:
  sdk: ">=1.14.0 <2.0.0"

dependencies:
  dart2_constant: ^1.0.1
  fluri: ^1.2.2
  http_parser: '>=2.2.0 <4.0.0'
  meta: ^1.1.0
  mime: ^0.9.3
  sockjs_client:
    git:
      url: git://github.com/Workiva/sockjs-dart-client.git
      ref: 0.3.3
  sockjs_client_wrapper: ^1.0.4

dev_dependencies:
  browser: ^0.10.0+2
  # TODO: use these once we move to Dart 2
#  build_runner: ^0.8.2
#  build_test: ^0.10.1
#  build_web_compilers: ^0.3.6
  collection: ^1.14.6
  coverage: ^0.10.0
  dart_dev: ^1.7.7
  dart_style: ^1.0.6
  dependency_validator: ^1.0.0
  http_server: ^0.9.6
  mockito: ^2.0.2
  over_react: ^1.24.0
  test: ^0.12.32+1
  uuid: ^0.5.3

transformers:
- over_react:
    $include: example/**.dart
- test/pub_serve:
    $include: test/**_test.dart

web:
  compiler:
    debug: dartdevc
