name: w_transport
version: 4.0.10
description: Transport library for sending HTTP requests and opening WebSockets. Platform-independent with builtin support for browser and Dart VM (even supports SockJS). Includes mock utilities for testing.
homepage: https://github.com/Workiva/w_transport

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  fluri: ^1.2.6
  http_parser: ^3.1.3
  meta: ^1.2.2
  mime: '>=0.9.6+3 <2.0.0'
  quiver: '>=2.1.5 <4.0.0'
  sockjs_client_wrapper: ^1.0.14

dev_dependencies:
  build_runner: '>=1.11.1+1 <3.0.0'
  build_test: ^1.3.6
  build_web_compilers: ^2.16.3
  collection: ^1.14.6
  dart_dev: ^3.7.0
  dart_style: '>=1.3.12 <3.0.0'
  dependency_validator: '>=2.0.0 <4.0.0'
  http_server: ^0.9.8+3
  mockito: ^4.1.1
  over_react: ^4.0.0
  test: ^1.16.5
  uuid: ^3.0.5
  workiva_analysis_options: ^1.0.2
