name: w_transport
version: 3.2.9
description: Transport library for sending HTTP requests and opening WebSockets. Platform-independent with builtin support for browser and Dart VM (even supports SockJS). Includes mock utilities for testing.
homepage: https://github.com/Workiva/w_transport

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  fluri: ^1.2.6
  http_parser: ^3.1.3
  meta: ^1.1.8
  mime: ^0.9.6+3
  sockjs_client:
    git:
      url: git://github.com/Workiva/sockjs-dart-client.git
      ref: 0.3.5
  sockjs_client_wrapper: ^1.0.14

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^1.0.9
  build_web_compilers: ^2.6.1
  collection: ^1.14.6
  dart_dev: ^3.3.1
  dart_style: ^1.3.1
  dependency_validator: ^1.4.1
  http_server: ^0.9.8+3
  mockito: ^4.1.1
  over_react: ">=3.12.0 <5.0.0"
  test: ^1.15.2
  uuid: ^2.0.4
  workiva_analysis_options: ^1.0.2
