name: w_transport
version: 2.0.1
description: >
  Platform-agnostic transport library for sending and receiving data over HTTP
  and WebSocket. HTTP support includes plain-text, JSON, form-data, and
  multipart data, as well as custom encoding. WebSocket support includes native
  WebSockets in the browser and the VM with the option to use SockJS in the
  browser.
authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Dustin Lessard <dustin.lessard@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Jay Udey <jay.udey@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>
homepage: https://github.com/Workiva/w_transport
dependencies:
  fluri: "^1.1.0"
  http_parser: "^1.0.0"
  mime: "^0.9.3"
  sockjs_client:
    git:
      url: https://github.com/Workiva/sockjs-dart-client.git
      ref: 0.3.0
  stack_trace: "^1.4.0"
dev_dependencies:
  ansicolor: "^0.0.9"
  args: "^0.13.0"
  browser: "^0.10.0+2"
  coverage: "^0.7.2"
  dart_dev: "^1.0.0"
  dart_style: "^0.2.1"
  dartdoc: ">=0.4.0 <0.7.0"
  http_server: "^0.9.5+1"
  mockito: "^0.9.0"
  path: "^1.3.5"
  react: "^0.6.1"
  test: "^0.12.3+5"
  uuid: "^0.5.0"
environment:
  sdk: ">=1.9.0 <2.0.0"
